ProyectoDesarrollow/src/main/java/Controller/AperitivoController.java
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Controller;

import gestion.AperitivoGestion;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import modelo.Aperitivo;

@Named(value = "aperitivoController")
@SessionScoped
public class AperitivoController extends Aperitivo implements Serializable {

    public AperitivoController() {
    }
    
    public List<Aperitivo> getAperitivos(){
        return AperitivoGestion.getAperitivos();
    }
}

ProyectoDesarrollow/src/main/java/Controller/ClienteController.java
package Controller;

import gestion.ClienteGestion;
import gestion.UsuarioGestion;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import modelo.Cliente;

@Named(value = "clienteController")
@SessionScoped
public class ClienteController extends Cliente implements Serializable {

    public ClienteController() {
    }
    
    public String insert(String usuario, String password){
        if (ClienteGestion.insert(this)){
            this.setId(ClienteGestion.getLastCliente());
            
            if (UsuarioGestion.insert(this.getId(), usuario, password)){
                
                return "account.xhtml";
            }else {
                FacesMessage mensaje= new FacesMessage (FacesMessage.SEVERITY_ERROR,
                "Error","Posible identificación duplicada");
                FacesContext.getCurrentInstance().addMessage("registroClienteForm:idUsuario", mensaje);
                
                return "index.xhtml";   
            }
        }else {
            FacesMessage mensaje= new FacesMessage (FacesMessage.SEVERITY_ERROR, 
            "Error", "Posible Cédula duplicada...");
            FacesContext.getCurrentInstance().addMessage("registroClienteForm:cedula", mensaje);
            
            return "index.xhtml";      
        }
    }
}

ProyectoDesarrollow/src/main/java/Controller/ReporteController.java
package Controller;

import java.io.File;
import java.io.IOException;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.faces.context.FacesContext;
import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletResponse;
import modelo.Conexion;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;


@Named(value = "reporteController")
@SessionScoped
public class ReporteController implements Serializable {

    public ReporteController() {
    }
    
    public void show(){
        try {
            File jasper = new File(FacesContext.getCurrentInstance().getExternalContext().getRealPath("/lounge/LoungeReport.jasper"));
            
            JasperPrint reporteJasper = JasperFillManager.fillReport(jasper.getPath(), null, Conexion.getConexion());
            HttpServletResponse respuesta = (HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
            
            respuesta.setContentType("application/pdf");
            respuesta.addHeader("Content-Type", "application/pdf");
            ServletOutputStream flujo = respuesta.getOutputStream();
            JasperExportManager.exportReportToPdfStream(reporteJasper, flujo);
            FacesContext.getCurrentInstance().responseComplete();
            
        } catch (JRException ex) {
            Logger.getLogger(ReporteController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ReporteController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void download(){
        try {
            File jasper= new File (FacesContext.getCurrentInstance().getExternalContext().getRealPath("/lounge/LoungeReport.jasper"));
            
            JasperPrint reporteJasper = JasperFillManager.fillReport(jasper.getPath(), null, Conexion.getConexion());
            HttpServletResponse respuesta = (HttpServletResponse)FacesContext.getCurrentInstance().getExternalContext().getResponse();
            
            respuesta.addHeader("Content-disposition", "attachement; filename=Lounge.pdf");
            ServletOutputStream flujo = respuesta.getOutputStream();
            JasperExportManager.exportReportToPdfStream(reporteJasper, flujo);
            FacesContext.getCurrentInstance().responseComplete();
            
        } catch (JRException ex) {
            Logger.getLogger(ReporteController.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(ReporteController.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}

ProyectoDesarrollow/src/main/java/Controller/ReservaController.java
package Controller;

import gestion.ReservaGestion;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import modelo.Reserva;

@Named(value = "reservaController")
@SessionScoped
public class ReservaController extends Reserva implements Serializable {

    public ReservaController() {
    }
    
    public List<Reserva> getReservas(int idUsuario){
        return ReservaGestion.getReservacionesByUser(idUsuario);
    }
    
    public void insert(int idRuta, int idUsuario){
        if (ReservaGestion.insert(idRuta, idUsuario)){
            
        }else {
            FacesMessage mensaje= new FacesMessage (FacesMessage.SEVERITY_ERROR,
            "Error","Posible identificación duplicada");
            FacesContext.getCurrentInstance().addMessage("rutaList:reservar", mensaje);
        }
    }
    
    public String delete(int id){
        if (ReservaGestion.delete(id)){
            return "reserva.xhtml";
        }else {
            FacesMessage mensaje= new FacesMessage (FacesMessage.SEVERITY_ERROR,
            "Error","Posiblemente el id no exista en base de datos");
            FacesContext.getCurrentInstance().addMessage("editaEsperaForm:identificacion", mensaje);
            
            return "index.xhtml";
        }
    }
}

ProyectoDesarrollow/src/main/java/Controller/RutaController.java
package Controller;

import gestion.ProvinciaGestion;
import gestion.RutaGestion;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import java.util.List;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import modelo.Ruta;

@Named(value = "rutaController")
@SessionScoped
public class RutaController extends Ruta implements Serializable {

    public RutaController() {
    }
    
    public List<Ruta> getRutasSanJose(int idUsuario){
        return RutaGestion.getRutasSanJose(idUsuario);
    }
    
    public List<Ruta> getRutasAlajuela(int idUsuario){
        return RutaGestion.getRutasAlajuela(idUsuario);
    }
    
    public List<Ruta> getRutasCartago(int idUsuario){
        return RutaGestion.getRutasCartago(idUsuario);
    }
    
    public List<Ruta> getRutasHeredia(int idUsuario){
        return RutaGestion.getRutasHeredia(idUsuario);
    }
    
    public List<Ruta> getRutasGuanacaste(int idUsuario){
        return RutaGestion.getRutasGuanacaste(idUsuario);
    }
    
    public List<Ruta> getRutasPuntarenas(int idUsuario){
        return RutaGestion.getRutasPuntarenas(idUsuario);
    }
    
    public List<Ruta> getRutasLimon(int idUsuario){
        return RutaGestion.getRutasLimon(idUsuario);
    }
     
    public String edit(int id){
        Ruta ruta = RutaGestion.getRuta(id);
         
        if (ruta != null){
            this.setId(ruta.getId());
            this.setProvincia(ProvinciaGestion.getProvincia(id));
            this.setNombre(ruta.getNombre());
            this.setHorario(ruta.getHorario());
            this.setFecha(ruta.getFecha());
            this.setDuracion(ruta.getDuracion());
            this.setParada(ruta.getParada());
            this.setPrecio(ruta.getPrecio());
             
            return "edita.xhtml";
         }else{
            FacesMessage mensaje= new FacesMessage (FacesMessage.SEVERITY_ERROR,
            "Error","Posiblemente el id no exista en base de datos");
            FacesContext.getCurrentInstance().addMessage("editaRutaForm:idRuta", mensaje);
            
            return "list.xhtml";
        }
    }
}

ProyectoDesarrollow/src/main/java/Controller/UsuarioController.java
package Controller;

import gestion.ClienteGestion;
import gestion.UsuarioGestion;
import javax.inject.Named;
import javax.enterprise.context.SessionScoped;
import java.io.Serializable;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import modelo.Cliente;
import modelo.Usuario;

@Named(value = "usuarioController")
@SessionScoped
public class UsuarioController extends Usuario implements Serializable {
   
    public UsuarioController() {
    }
    
    public String valida(){
        Usuario usuario = UsuarioGestion.validate(this.getUsuario(), this.getPassword());
        
        if (usuario != null){
            Cliente cliente = ClienteGestion.getCliente(usuario.getId());

            this.setId(usuario.getId());
            this.setCliente(usuario.getCliente());
            this.setUsuario(usuario.getUsuario());
            this.setPassword(usuario.getPassword());
            this.setIdRol(usuario.getIdRol());
            this.setCliente(cliente);
            
            return "index.xhtml";
        }else{
            FacesMessage msg = new FacesMessage (FacesMessage.SEVERITY_ERROR, "Error", "Usuario o "
                    + "Contraseña inválidas");
            FacesContext.getCurrentInstance().addMessage("loginForm:usuario", msg);
            
            return "logIn.xhtml";
        }
    }
    
}

ProyectoDesarrollow/src/main/webapp/account.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    
    <h:head>
        <title>Account</title>
        <h:outputStylesheet library="css" name="logincss.css"/>

        <style>
            .centrado{ 
                position:absolute;
                top: 40%;
                left: 45%;
                bottom:0;
                width: 630px;
                height: 550px;
                margin: auto;
                margin-left: -200px;
                margin-top: -150px;
            }   
        </style>
    </h:head>
    
    <h:body>
        <div id="particles-js">
            <h:form id="accountInfo">
                <b:panel title="Cuenta creada correctamente" look="info" style-class="centrado">
                    <b:row>
                        <b:column medium-screen="4"/>

                        <b:column medium-screen="6">
                            <h:outputLabel value="Informacion sobre la cuenta"/>
                        </b:column>
                    </b:row>

                    <b:row>
                        <b:column medium-screen="2"/>

                        <b:column medium-screen="4">
                            <p:barcode value="#{usuarioController.toString(clienteController)}" type="qr"  width="400px"/>
                        </b:column>
                    </b:row>

                    <b:row>
                        <b:column medium-screen="4"/>

                        <b:column medium-screen="4">
                            <b:commandLink value="Log In" 
                                           look="primary"
                                           href="/ProyectoDesarrollow-1/faces/logIn.xhtml"/>
                        </b:column>
                    </b:row>
                </b:panel>
            </h:form>
        </div>
    </h:body>
    
    <h:outputScript library = "js" name = "particles.js"></h:outputScript>
    <h:outputScript library = "js" name = "app.js"></h:outputScript>
</html>

ProyectoDesarrollow/src/main/webapp/aperitivoslist.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">
    
    <body>
        <ui:composition template="./resources/plantillas/plantilla.xhtml">
            <ui:define name="content">
                <h:form>
                    <div id="content" class="left_content">
                        <h1 class="section-header_2">Aperitivos</h1>
                        <hr style="border-color: #337ab7"/>
                        
                        <b:dataTable value="#{aperitivoController.aperitivos}"
                                     var="aperitivo"
                                     excel="true"
                                     csv="true"
                                     pdf="true"
                                     columnVisibility="true"
                                     copy="true"
                                     print="true">
                            <b:dataTableColumn value="#{aperitivo.idPlato}"
                                               width="8%"
                                               label="Codigo"/>

                            <b:dataTableColumn value="#{aperitivo.plato}"
                                               width="19%"
                                               label="Aperitivo"/>

                            <b:dataTableColumn value="#{aperitivo.precio}"
                                               width="19%"
                                               label="Precio">
                            </b:dataTableColumn>
                        </b:dataTable>
                    </div>
                </h:form>
            </ui:define>
        </ui:composition>
    </body>
</html>

ProyectoDesarrollow/src/main/webapp/contacto.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <body>
        <h:outputStylesheet library="css" name="general.css"/>
        <ui:composition template="./resources/plantillas/plantilla.xhtml">
            <ui:define name="content">
                <div id="content" class="left_content">
                    <h1 class="section-header">¿Dónde nos encontramos?</h1>
                    <hr style="border-color: #337ab7"/>
                    
                    <iframe src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d125770.8028777803!2d-84.1520095009879!3d9.905815631848544!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x8fa0e3f47ea4ff37%3A0x7a7818a6a9e5c90c!2sUniversidad%20Fid%C3%A9litas!5e0!3m2!1ses-419!2scr!4v1627949602212!5m2!1ses-419!2scr" width="1860" height="600" style="border:0;" allowfullscreen="" loading="lazy"></iframe>
                    
                    <br/>
                    <hr/>
                    <section id="contactUs">
                        <section id="contact">

                            <h3 class="section-header">Contacto</h3>

                            <div class="contact-wrapper">
                                <form id="contact-form" class="form-horizontal" role="form">
                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <input type="text" class="form-control" id="name" placeholder="NOMBRE" name="name" value="" required='true'></input>
                                        </div>
                                    </div>

                                    <div class="form-group">
                                        <div class="col-sm-12">
                                            <input type="email" class="form-control" id="email" placeholder="EMAIL" name="email" value="" required='true'></input>
                                        </div>
                                    </div>

                                    <textarea class="form-control" rows="10" placeholder="MENSAJE" name="message" required='true'></textarea>

                                    <button class="btn btn-primary send-button" id="submit" type="submit" value="SEND">
                                        <div class="alt-send-button">
                                            <i class="fa fa-paper-plane"></i><span class="send-text">ENVIAR</span>
                                        </div>
                                    </button>
                                </form>

                                <div class="direct-contact-container">
                                    <ul class="contact-list">
                                        <li class="list-item"><i class="fa fa-map-marker fa-2x"><span class="contact-text place">San Pedro, San Jose</span></i></li>

                                        <li class="list-item"><i class="fa fa-phone fa-2x"><span class="contact-text phone"><a href="tel:1-212-555-5555" title="Llamar">(506) 8728-1968</a></span></i></li>

                                        <li class="list-item"><i class="fa fa-envelope fa-2x"><span class="contact-text gmail"><a href="mailto:#" title="Enviar correo">busdrivecontacto@gmail.com</a></span></i></li>

                                    </ul>

                                    <hr style="border-color: #000;"/>
                                    
                                    <ul class="social-media-list">
                                        <li><a href="#" target="_blank" class="contact-icon">
                                                <i class="fa fa-facebook" aria-hidden="true"></i></a>
                                        </li>
                                        <li><a href="#" target="_blank" class="contact-icon">
                                                <i class="fa fa-twitter" aria-hidden="true"></i></a>
                                        </li>
                                        <li><a href="#" target="_blank" class="contact-icon">
                                                <i class="fa fa-instagram" aria-hidden="true"></i></a>
                                        </li>       
                                    </ul>
                                    <hr style="border-color: #000;"/>
                                </div>
                            </div>
                        </section>
                    </section>
                </div>
            </ui:define>
        </ui:composition>
        
        <h:outputScript library = "js" name = "general.js"></h:outputScript>
    </body>
</html>

ProyectoDesarrollow/src/main/webapp/empresa.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">


    <body>
        <h:outputStylesheet library="css" name="general.css"/>
        <ui:composition template="./resources/plantillas/plantilla.xhtml">
            <ui:define name="content">
                <h1 class="section-header">Sobre Nosotros</h1>
                <hr style="border-color: #337ab7"/>
                
                <b:carousel id="bus" style="height: auto; width: auto;">
                    <b:carouselItem>
                        <h:graphicImage library="imagen" name="7.jpg" alt="trabajadores" />
                    </b:carouselItem>
                    <b:carouselItem>
                        <h:graphicImage library="imagen" name="8.jpg" alt="trabajadores2" />
                    </b:carouselItem>
                    <b:carouselItem>
                        <h:graphicImage library="imagen" name="9.jpg" alt="trabajadores3" />
                    </b:carouselItem>
                </b:carousel>

                <div id="content" class="left_content">
                    <h1 class="section-header">El lujo de un avión por tierra </h1>
                    <hr/>
                    <br/>
                    <p style="font-size: 15px;" align="justify" >
                        Somos una empresa familiar dedicada a brindar transporte público de calidad en Costa Rica.
                        Velamos por el bienestar de nuestras comunidades, especialmente nuestros vecinos, amigos
                        y familiares que confían en nosotros y nuestro equipo para transportarlos de manera segura.

                        Nos esforzamos diariamente por mejorar nuestras comunidades a través de proporcionar los servicios 
                        de transporte más seguros, amigables con el ambiente, y confiables posible. Como líderes en el negocio
                        del transporte seguro y profesional de pasajeros, nos sentimos muy orgullosos de asegurarnos que sus 
                        necesidades específicas sean atendidas.
                    </p> 
                </div>

                <br/>
                
                <section class="text-center about">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-4 col-sm-6 col-ex-12 about-item wow lightSpeedIn" data-wow-offset="200" >
                                <span class="fa fa-check"></span>
                                <h2>Misión</h2>
                                <p class="lead" align="justify" >
                                    Juntos conectamos la región al proporcionar una red de transporte comprometida 
                                    al medio ambiente, mejorando la calidad de vida al unir personas y comunidades.
                                </p>
                            </div>
                            
                            <div class="col-lg-4 col-sm-6 col-ex-12 about-item wow lightSpeedIn" data-wow-offset="200">
                                <span class="fa fa-eye"></span>
                                <h2>Visión</h2>
                                <p class="lead" align="justify">Proveer un sistema integrado de servicios de 
                                    transporte público innovadores, accesibles y 
                                    eficientes que aumenten el acceso a las oportunidades y contribuyan a un
                                    ambiente saludable
                                    para las personas de Costa Rica.
                                </p>
                            </div>
                            
                            <div class="clearfix visible-md-block visible-sm-block"></div>
                            
                            <div class="col-lg-4 col-sm-6 col-ex-12 about-item wow lightSpeedIn" data-wow-offset="200">
                                <span class="fa fa-heart"></span>
                                <h2>Valores</h2>
                                <p class="lead" align="justify" >Proveer un sistema integrado de servicios de transporte público innovadores, accesibles y 
                                    eficientes que aumenten el acceso a las oportunidades y contribuyan a un ambiente saludable
                                    para las personas de Costa Rica.
                                </p>
                            </div>
                        </div>
                    </div>
                </section>
            </ui:define>
        </ui:composition>
    </body>
</html>

ProyectoDesarrollow/src/main/webapp/logIn.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://xmlns.jcp.org/jsf/html"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets">
    
    <h:head>
        <title>Log In</title>
        <h:outputStylesheet library="css" name="logincss.css"/>

        <style>
            .centrado{ 
                position:absolute;
                top:50%;
                left: 50%;
                bottom:0;
                width: 400px;
                height: 300px;
                margin: auto;
                margin-left: -200px;
                margin-top: -150px;
            }   
        </style>

    </h:head>
    
    <h:body>
        <div id="particles-js">
            <h:form id="loginForm" > 
                <b:panel title="Log In" look="info" collapsed="false"  style-class="centrado">
                    <b:row>
                        <b:column medium-screen="1"/>
                        
                        <b:column medium-screen="10">
                            <b:inputText placeholder="Usuario"
                                         id="usuario"
                                         required="true"
                                         autocomplete="true"
                                         value="#{usuarioController.usuario}">
                                <f:facet name="prepend">
                                    <b:icon name="user"/>
                                </f:facet>
                            </b:inputText>
                        </b:column>
                    </b:row>
                    
                    <b:row>
                        <b:column medium-screen="1"/>
                        
                        <b:column medium-screen="10" style-class="usuario">
                            <b:message for="usuario"/>
                        </b:column>
                        
                        <b:column medium-screen="1"/>
                    </b:row>

                    <b:row>
                        <b:column medium-screen="1"/>
                        
                        <b:column medium-screen="10">
                            <b:inputSecret placeholder="Clave"
                                           id="clave"
                                           required="true"
                                           autocomplete="true"
                                           value="#{usuarioController.password}">
                                <f:facet name="prepend">
                                    <b:iconAwesome name="key"/>
                                </f:facet>
                            </b:inputSecret>
                        </b:column>
                        
                        <b:column medium-screen="1" style-class="message">
                            <b:message for="clave"/>
                        </b:column>
                    </b:row>

                    <b:row>
                        <b:column medium-screen="2"/>
                        <b:column medium-screen="8">
                                <b:commandButton value="Log In"
                                                 look="primary"
                                                 style="width: 100%"
                                                 action="#{usuarioController.valida()}"/>
                        </b:column>
                    </b:row>
                    
                    <br/>
                    
                    <b:row>
                        <b:column medium-screen="2"/>
                        <b:column medium-screen="8">
                                <b:commandLink value="Sign In" 
                                               look="default" 
                                               style="width: 100%"
                                               href="/ProyectoDesarrollow-1/faces/signIn.xhtml"/>
                        </b:column>
                    </b:row>
                </b:panel>
            </h:form>
        </div>
    </h:body>

    <!-- scripts -->
    <h:outputScript library = "js" name = "particles.js"></h:outputScript>
    <h:outputScript library = "js" name = "app.js"></h:outputScript>
</html>

ProyectoDesarrollow/src/main/webapp/reporte.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://xmlns.jcp.org/jsf/facelets"
      xmlns:b="http://bootsfaces.net/ui"
      xmlns:f="http://xmlns.jcp.org/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:h="http://xmlns.jcp.org/jsf/html">

    <h:body>
         <ui:composition template="./resources/plantillas/plantilla.xhtml">
            <ui:define name="content">
                <b:form>
                    <b:container fluid="true">
                        <div id="content" class="left_content">
                            <h1 class="section-header_2">Lounge</h1>
                            <hr style="border-color: #337ab7"/>

                            <b:panel title="Terminales" look="primary">
                                <b:row>
                                    <b:column medium-screen="3">
                                        <h:outputLabel value="Archivo con las diferentes terminales de Bus Drive" for="pdf"/>
                                    </b:column>
                                    <b:column medium-screen="3">
                                        <b:commandButton value="Ver en PDF"
                                                         action="#{reporteController.show()}"/>&nbsp;
                                        <b:commandButton value="Descargar en PDF"
                                                         action="#{reporteController.download()}"/>
                                    </b:column>

                                </b:row>
                            </b:panel>
                        </div>
                    </b:container>
                </b:form>
            </ui:define>
        </ui:composition>
    </h:body>
</html>